USE QCM_DB

SELECT TOP 1000 [idTheme]
      ,[libelle]
  FROM [QCM_DB].[dbo].[THEME]

INSERT INTO THEME VALUES ('Objet Java EE');
INSERT INTO THEME VALUES ('Héritage Java EE');
INSERT INTO THEME VALUES ('Interface Java EE');
INSERT INTO THEME VALUES ('Classes Java EE');
INSERT INTO THEME VALUES ('Présentation Java EE');
INSERT INTO THEME VALUES ('Requête SQL');
INSERT INTO THEME VALUES ('Procédure stockée SQL');
INSERT INTO THEME VALUES ('Les bases du SQL');
INSERT INTO THEME VALUES ('Les jointures SQL');
INSERT INTO THEME VALUES ('Les fonctions SQL');
INSERT INTO THEME VALUES ('Les bases du PL-SQL');
INSERT INTO THEME VALUES ('Les transactions PL-SQL');
INSERT INTO THEME VALUES ('La gestion des erreurs PL-SQL');
INSERT INTO THEME VALUES ('PL-SQL avancé');
INSERT INTO THEME VALUES ('Les curseurs en PL-SQL');
INSERT INTO THEME VALUES ('Les bases du HTML');
INSERT INTO THEME VALUES ('Les forumulaires HTML');
INSERT INTO THEME VALUES ('Les attributs HTML');
INSERT INTO THEME VALUES ('HTML avancé');
INSERT INTO THEME VALUES ('Les styles HTML');
INSERT INTO THEME VALUES ('Présentation Javascript');
INSERT INTO THEME VALUES ('Les objets Javascript');
INSERT INTO THEME VALUES ('Le Design Pattern Javascript');
INSERT INTO THEME VALUES ('Javascript et AJAX');
INSERT INTO THEME VALUES ('Javascript et HTML');

INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,6);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,6);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,6);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,6);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,6);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,6);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,6);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,6);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,6);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,6);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,7);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,7);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,7);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,7);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,7);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,7);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,7);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,7);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,7);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,7);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,8);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,8);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,8);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,8);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,8);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,8);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,8);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,8);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,8);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,8);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,9);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,9);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,9);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,9);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,9);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,9);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,9);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,9);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,9);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,9);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,10);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,10);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,10);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,10);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,10);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,10);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,10);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,10);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,10);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,10);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,11);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,11);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,11);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,11);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,11);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,11);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,11);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,11);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,11);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,11);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,12);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,12);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,12);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,12);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,12);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,12);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,12);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,12);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,12);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,12);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,13);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,13);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,13);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,13);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,13);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,13);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,13);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,13);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,13);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,13);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,14);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,14);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,14);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,14);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,14);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,14);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,14);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,14);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,14);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,14);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,15);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,15);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,15);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,15);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,15);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,15);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,15);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,15);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,15);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,15);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,16);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,16);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,16);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,16);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,16);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,16);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,16);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,16);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,16);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,16);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,17);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,17);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,17);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,17);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,17);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,17);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,17);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,17);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,17);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,17);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,18);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,18);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,18);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,18);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,18);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,18);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,18);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,18);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,18);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,18);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,19);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,19);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,19);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,19);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,19);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,19);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,19);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,19);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,19);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,19);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,20);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,20);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,20);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,20);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,20);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,20);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,20);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,20);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,20);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,20);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,21);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,21);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,21);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,21);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,21);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,21);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,21);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,21);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,21);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,21);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,22);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,22);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,22);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,22);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,22);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,22);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,22);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,22);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,22);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,22);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,23);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,23);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,23);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,23);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,23);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,23);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,23);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,23);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,23);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,23);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,24);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,24);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,24);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,24);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,24);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,24);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,24);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,24);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,24);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,24);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,25);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,25);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,25);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,25);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,25);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,25);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,25);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,25);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,25);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,25);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,26);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,26);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,26);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,26);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,26);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,26);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,26);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,26);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,26);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,26);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,27);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,27);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,27);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,27);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,27);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,27);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,27);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,27);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,27);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,27);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,28);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,28);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,28);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,28);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,28);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,28);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,28);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,28);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,28);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,28);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,29);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,29);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,29);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,29);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,29);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,29);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,29);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,29);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,29);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,29);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé1',1,30);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé2',1,30);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé3',1,30);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé4',1,30);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé5',1,30);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé6',1,30);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé7',1,30);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé8',1,30);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé9',1,30);
INSERT INTO QUESTION(enonce,points,idTheme) VALUES ('enoncé10',1,30);